//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks.Std {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Std.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /* eslint-disable */
        ///// Was generated by gfwlist2pac in precise mode
        ///// https://github.com/clowwindy/gfwlist2pac
        ///
        ///// 2019-10-06: More &apos;javascript&apos; way to interaction with main program
        ///// 2019-02-08: Updated to support shadowsocks-windows user rules.
        ///
        ///var proxy = __PROXY__;
        ///var userrules = __USERRULES__;
        ///var rules = __RULES__;
        ///
        ////*
        ///* This file is part of Adblock Plus &lt;http://adblockplus.org/&gt;,
        ///* Copyright (C) 2006-2014 Eyeo GmbH
        ///*
        ///* Adblock Plus is free software: you can redistribute it and/or  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string abp_js {
            get {
                return ResourceManager.GetString("abp_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var __USERRULES__ = [];
        ///var __RULES__ = [
        ///    &quot;|http://85.17.73.31/&quot;,
        ///    &quot;||agnesb.fr&quot;,
        ///    &quot;||akiba-web.com&quot;,
        ///    &quot;||altrec.com&quot;,
        ///    &quot;||angela-merkel.de&quot;,
        ///    &quot;||angola.org&quot;,
        ///    &quot;||apartmentratings.com&quot;,
        ///    &quot;||apartments.com&quot;,
        ///    &quot;||arena.taipei&quot;,
        ///    &quot;||asianspiss.com&quot;,
        ///    &quot;||assimp.org&quot;,
        ///    &quot;||athenaeizou.com&quot;,
        ///    &quot;||azubu.tv&quot;,
        ///    &quot;||bankmobilevibe.com&quot;,
        ///    &quot;||banorte.com&quot;,
        ///    &quot;||bash-hackers.org&quot;,
        ///    &quot;||beeg.com&quot;,
        ///    &quot;||global.bing.com&quot;,
        ///    &quot;||bloombergview.com&quot;,
        ///    &quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string abp_rule_js {
            get {
                return ResourceManager.GetString("abp_rule_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 en,zh-CN,zh-TW,ja
        ///#Restart program to apply translation,,,
        ///#This is comment line,,,
        ///#Always keep language name at head of file,,,
        ///#Language name is output in log,,,
        ///&quot;#You can find it by search &quot;&quot;Current language is:&quot;&quot;&quot;,,,
        ///#Please use UTF-8 with BOM encoding so we can edit it in Excel,,,
        ///,,,
        ///# Messages,,,
        ///,,,
        ///Shadowsocks Error: {0},Shadowsocks 错误: {0},Shadowsocks 錯誤: {0},Shadowsocks エラー: {0}
        ///Port {0} already in use,端口 {0} 已被占用,連接埠號碼 {0} 已被使用,ポート番号 {0} は既に使用されています。
        ///Port {0} is reserved by system,端 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string i18n_csv {
            get {
                return ResourceManager.GetString("i18n_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 listen-address __PRIVOXY_BIND_IP__:__PRIVOXY_BIND_PORT__
        ///toggle 0
        ///logfile ss_privoxy.log
        ///show-on-task-bar 0
        ///activity-animation 0
        ///forward-socks5 / __SOCKS_HOST__:__SOCKS_PORT__ .
        ///max-client-connections 2048
        ///hide-console
        /// 的本地化字符串。
        /// </summary>
        internal static string privoxy_conf {
            get {
                return ResourceManager.GetString("privoxy_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ! Put user rules line by line in this file.
        ///! See https://adblockplus.org/en/filter-cheatsheet
        /// 的本地化字符串。
        /// </summary>
        internal static string user_rule {
            get {
                return ResourceManager.GetString("user_rule", resourceCulture);
            }
        }
    }
}
